"""
Central configuration for FAIR-PATH AI Career Intelligence Platform.
"""
import os
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ── Load .env file (if present) so API keys persist across sessions ────
_env_path = BASE_DIR / ".env"
if _env_path.exists():
    with open(_env_path, encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if not _line or _line.startswith("#") or "=" not in _line:
                continue
            _key, _, _val = _line.partition("=")
            _key, _val = _key.strip(), _val.strip()
            if _val and _key not in os.environ:
                os.environ[_key] = _val

DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

SKILLS_VOCAB_PATH = PROCESSED_DIR / "skills_vocabulary.csv"
RESUME_SKILLS_PATH = PROCESSED_DIR / "resume_skills.csv"
JOBS_PARSED_PATH = PROCESSED_DIR / "jobs_parsed.csv"
SKILL_TRENDS_PATH = PROCESSED_DIR / "skill_trends.csv"
JOBS_DB_PATH = PROCESSED_DIR / "jobs_collected.csv"

# ── Model settings ─────────────────────────────────────────────────────
ROBERTA_MODEL = "jjzha/jobbert_skill_extraction"
SBERT_MODEL = "all-MiniLM-L6-v2"
NER_CONFIDENCE = 0.65
NER_CHUNK_SIZE = 500
DEVICE = -1  # -1 = CPU, 0 = GPU

# ── Matching weights ───────────────────────────────────────────────────
SEMANTIC_WEIGHT = 0.50
SKILL_OVERLAP_WEIGHT = 0.30
EXPERIENCE_WEIGHT = 0.20
REQUIRED_SKILL_W = 0.70
PREFERRED_SKILL_W = 0.30

# ── Job API configuration ─────────────────────────────────────────────
JSEARCH_API_KEY = os.getenv("JSEARCH_API_KEY", "")
JSEARCH_BASE_URL = "https://jsearch.p.rapidapi.com"
ADZUNA_APP_ID = os.getenv("ADZUNA_APP_ID", "")
ADZUNA_APP_KEY = os.getenv("ADZUNA_APP_KEY", "")
ADZUNA_BASE_URL = "https://api.adzuna.com/v1/api/jobs"
REMOTIVE_BASE_URL = "https://remotive.com/api/remote-jobs"
SERPAPI_KEY = os.getenv("SERPAPI_KEY", "")

# ── Fairness settings ─────────────────────────────────────────────────
FAIRNESS_BIAS_CATEGORIES = {
    "Gender Bias": {
        "indicators": [
            "male", "female", "gender", "mr.", "mrs.", "ms.",
            "he/him", "she/her", "man", "woman",
        ],
        "penalty": 10,
    },
    "Age Bias": {
        "indicators": [
            "age", "years old", "born in", "date of birth", "dob",
            "young", "senior citizen",
        ],
        "penalty": 10,
    },
    "Ethnicity / Nationality Bias": {
        "indicators": [
            "nationality", "race", "ethnicity", "religion", "caste",
            "country of origin",
        ],
        "penalty": 10,
    },
    "Marital / Family Bias": {
        "indicators": [
            "marital status", "married", "single", "divorced",
            "children", "family", "spouse",
        ],
        "penalty": 8,
    },
    "Photo / Appearance Bias": {
        "indicators": ["photo", "picture", "image", "headshot", "portrait"],
        "penalty": 8,
    },
    "Education Prestige Bias": {
        "indicators": ["ivy league", "top university", "tier 1", "tier-1"],
        "penalty": 5,
    },
}

# ── Skill category taxonomy (for UI grouping) ─────────────────────────
SKILL_CATEGORIES = {
    "Programming Languages": [
        "python", "java", "javascript", "c++", "c#", "c", "go", "rust",
        "typescript", "ruby", "php", "swift", "kotlin", "scala", "r",
        "sql", "html", "css", "perl", "matlab", "shell", "shell scripting",
        "powershell", "dart", "lua", "elixir", "haskell", "solidity",
        "vhdl", "verilog", "systemverilog", "assembly language", "assembly",
        "embedded c", "latex",
    ],
    "ML / AI": [
        "machine learning", "deep learning", "nlp",
        "natural language processing", "tensorflow", "pytorch", "keras",
        "neural networks", "reinforcement learning", "computer vision",
        "generative ai", "llm", "langchain", "llamaindex", "transformers",
        "hugging face", "prompt engineering", "fine-tuning",
        "stable diffusion", "multimodal ai", "blip", "openai", "groq",
        "ollama", "vllm", "rag", "retrieval-augmented generation",
        "scikit-learn", "xgboost", "lightgbm", "catboost",
        "opencv", "yolo", "object detection", "image classification",
        "text classification", "named entity recognition", "sentiment analysis",
        "recommendation systems", "time series", "feature engineering",
        "model deployment", "onnx", "tensorrt", "triton", "mlops",
        "cnn", "rnn", "lstm", "gan", "autoencoder", "attention mechanism",
        "bert", "gpt", "llama", "image processing", "digital image processing",
    ],
    "Electrical / Electronics": [
        "analog circuits", "digital circuits", "digital electronics",
        "signal processing", "digital signal processing", "dsp",
        "power electronics", "power systems", "electric machines",
        "electromagnetic", "em waves", "antenna design", "rf engineering",
        "communication systems", "wireless communication",
        "network theory", "circuit analysis", "circuit design",
        "information theory", "coding theory",
        "pwm", "pid", "pid controller", "control systems",
        "motor control", "dc motor", "stepper motor", "servo motor",
        "fourier transform", "fft", "wavelet transform", "z transform",
        "laplace transform", "radar", "sar", "synthetic aperture radar", "lidar",
        "semiconductor physics", "solid state physics",
        "optics", "photonics", "spectroscopy",
        "telecommunications", "5g", "lte", "fiber optics",
    ],
    "Embedded / Hardware": [
        "embedded systems", "fpga", "vlsi", "asic", "rtos", "firmware",
        "microcontroller", "microprocessor", "arduino", "raspberry pi",
        "stm32", "8051", "arm", "avr", "pic microcontroller",
        "cpld", "soc", "system on chip", "tiva", "msp430",
        "esp32", "esp8266", "nrf52",
        "pcb design", "pcb layout", "eagle", "kicad", "altium",
        "i2c", "spi", "uart", "can bus", "usb", "pcie",
        "soldering", "prototyping", "breadboard",
        "oscilloscope", "multimeter", "logic analyzer",
        "data acquisition", "instrumentation", "sensors",
        "signal conditioning", "adc", "dac",
    ],
    "IoT / Robotics": [
        "iot", "internet of things", "mqtt", "lora",
        "bluetooth", "wifi", "zigbee",
        "robotics", "ros", "robot operating system",
        "plc", "scada", "industrial automation",
    ],
    "EDA / Simulation Tools": [
        "spice", "ngspice", "ltspice", "pspice", "hspice",
        "cadence", "synopsys", "xilinx", "vivado", "quartus",
        "modelsim", "questasim", "simulink", "labview",
    ],
    "Mechanical Engineering": [
        "cad", "cam", "solidworks", "autocad", "catia", "creo",
        "unigraphics", "nx", "solidedge", "inventor", "freecad",
        "ansys", "abaqus", "comsol", "fluent", "cfd",
        "finite element analysis", "fea", "fem",
        "thermodynamics", "heat transfer", "fluid mechanics",
        "manufacturing", "cnc", "cnc machining", "3d printing",
        "additive manufacturing", "gd&t", "mechanical design",
        "materials science", "metallurgy", "composites",
        "vibration analysis", "structural analysis",
        "hvac", "piping", "pneumatics", "hydraulics",
        "strength of materials", "statics", "dynamics",
    ],
    "Civil Engineering": [
        "staad pro", "etabs", "revit", "primavera",
        "structural engineering", "geotechnical engineering",
        "surveying", "gis", "remote sensing",
        "concrete technology", "steel design",
        "construction management", "quantity surveying",
        "transportation engineering", "water resources",
        "environmental engineering", "soil mechanics",
        "building information modeling", "bim",
    ],
    "Chemical / Biomedical": [
        "aspen plus", "chemcad", "hysys",
        "process engineering", "process control",
        "chemical engineering", "reaction engineering",
        "biomedical engineering", "bioinformatics",
        "genomics", "proteomics", "molecular biology",
        "cell biology", "biochemistry", "microbiology",
        "drug discovery", "pharmacology",
    ],
    "Vector Databases / RAG": [
        "vector database", "chromadb", "pinecone", "weaviate",
        "faiss", "qdrant", "milvus",
    ],
    "Cloud / DevOps": [
        "aws", "azure", "gcp", "docker", "kubernetes", "jenkins",
        "ci/cd", "terraform", "ansible", "linux", "nginx", "grafana",
        "prometheus", "helm", "github actions", "gitlab ci",
        "istio", "elk stack", "cloudformation", "pulumi", "vagrant",
        "digitalocean", "vercel", "netlify", "apache",
    ],
    "Data Engineering / Science": [
        "data analysis", "statistics", "pandas", "numpy", "scipy",
        "data visualization", "tableau", "power bi", "spark", "hadoop",
        "kafka", "airflow", "etl", "big data", "snowflake", "dbt",
        "prefect", "dagster", "data pipeline", "data modeling",
        "data warehouse", "databricks", "matplotlib", "seaborn", "plotly",
        "looker", "spss", "minitab", "mathematica", "maple",
    ],
    "Web / Mobile": [
        "react", "angular", "vue", "node.js", "django", "flask",
        "android", "ios", "flutter", "next.js", "express", "graphql",
        "rest api", "fastapi", "streamlit", "gradio",
        "nuxt.js", "spring boot", "spring", "hibernate", ".net core",
        "blazor", "celery", "rabbitmq",
        "tailwind", "sass", "less", "webpack", "vite", "babel",
        "websockets", "oauth", "jwt", "three.js", "svelte", "remix",
        "astro", "react native", "swiftui", "jetpack compose",
    ],
    "Databases": [
        "mysql", "postgresql", "mongodb", "redis", "elasticsearch",
        "cassandra", "dynamodb", "oracle", "sql server", "neo4j",
        "supabase", "firebase", "influxdb", "timescaledb",
        "cockroachdb", "mariadb", "dbms",
    ],
    "CS Fundamentals": [
        "data structures", "algorithms", "object oriented programming",
        "operating systems", "computer networks", "system design",
        "design patterns", "solid principles", "clean architecture",
        "distributed systems", "microservices", "event driven architecture",
    ],
    "Math / Science": [
        "numerical methods", "linear algebra", "calculus",
        "differential equations", "probability", "optimization",
        "complex analysis", "quantum mechanics", "classical mechanics",
    ],
    "Tools": [
        "git", "github", "postman", "swagger", "jira", "notion", "figma",
        "vs code", "intellij", "pycharm", "vim", "neovim",
        "selenium", "cypress", "playwright", "jest", "pytest", "junit",
        "beautifulsoup", "scrapy", "puppeteer", "web scraping",
        "pygame", "tkinter", "qt", "electron",
        "bash", "cmake", "makefile", "gdb", "svn", "mercurial",
        "microsoft office", "excel", "overleaf",
        "android studio",
    ],
    "Soft Skills": [
        "communication", "teamwork", "leadership", "project management",
        "problem solving", "critical thinking", "time management",
        "presentation", "negotiation", "agile", "scrum", "kanban",
        "technical documentation", "code review", "technical writing",
        "operations research", "supply chain", "lean manufacturing",
        "six sigma", "quality control",
    ],
    "Energy / Sustainability": [
        "renewable energy", "solar energy", "wind energy",
        "energy storage", "battery technology",
        "electric vehicles", "ev",
        "aerospace engineering", "aerodynamics",
    ],
}

# ── Skill alias map (abbreviations → canonical) ───────────────────────
SKILL_ALIASES = {
    # ──── CORE TECH ABBREVIATIONS ────
    "ml": "machine learning",
    "ai": "artificial intelligence",
    "nlp": "natural language processing",
    "dl": "deep learning",
    "nn": "neural networks",
    "cv": "computer vision",
    "rl": "reinforcement learning",
    "js": "javascript",
    "ts": "typescript",
    "k8s": "kubernetes",
    "tf": "tensorflow",
    "aws": "aws",
    "gcp": "gcp",
    "devops": "devops",
    "ci cd": "ci/cd",
    "cicd": "ci/cd",
    "restapi": "rest api",
    "rest apis": "rest api",
    "postgres": "postgresql",
    "mongo": "mongodb",
    
    # ──── GENERAL TECH ────
    "oop": "object oriented programming",
    "oops": "object oriented programming",
    "llms": "llm",
    "large language model": "llm",
    "large language models": "llm",
    "rag": "retrieval-augmented generation",
    "retrieval augmented generation": "retrieval-augmented generation",
    "dsa": "data structures",
    "ds": "data structures",
    "os": "operating systems",
    "cn": "computer networks",
    "rdbms": "dbms",
    "database management": "dbms",
    "bs4": "beautifulsoup",
    "beautiful soup": "beautifulsoup",
    "sk learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "sci kit learn": "scikit-learn",
    "vscode": "vs code",
    "visual studio code": "vs code",
    "sb": "spring boot",
    "springboot": "spring boot",
    "dotnet": ".net",
    "dot net": ".net",
    
    # ──── MECHANICAL ENGINEERING ────
    "fea": "finite element analysis",
    "fem": "finite element analysis",
    "fe analysis": "finite element analysis",
    "fea analysis": "finite element analysis",
    "cfd": "computational fluid dynamics",
    "cfm": "computational fluid mechanics",
    "cad modeling": "cad",
    "autocadd": "autocad",
    "solidwork": "solidworks",
    "catia v5": "catia",
    "catia design": "catia",
    "nd": "solidworks",
    "3d cad": "3d modeling",
    "stress testing": "stress analysis",
    "modal testing": "modal analysis",
    "thermodynamic analysis": "thermodynamics",
    "thermal analysis": "thermodynamics",
    "sheet metal": "sheet metal design",
    "cnc programming": "cnc",
    "cnc machining": "cnc",
    "design for manufacturing": "design for manufacturing",
    "dfm": "design for manufacturing",
    "design for assembly": "design for assembly",
    "dfa": "design for assembly",
    "fmea": "failure mode analysis",
    "failure analysis": "failure mode analysis",
    "reliability engineering": "reliability engineering",
    "reliability analysis": "reliability engineering",
    "tolerance analysis": "tolerance analysis",
    "gear box design": "gear design",
    
    # ──── CIVIL ENGINEERING ────
    "rcc design": "reinforced concrete",
    "rc design": "reinforced concrete",
    "concrete structure": "reinforced concrete",
    "highway": "highway engineering",
    "road design": "road design",
    "traffic management": "traffic engineering",
    "transportation": "transportation engineering",
    "structure design": "structural design",
    "structural engineer": "structural engineering",
    "structure engineering": "structural engineering",
    "geotechnical": "geotechnical engineering",
    "geo technical": "geotechnical engineering",
    "geotechnics": "geotechnical engineering",
    "ground water": "groundwater assessment",
    "water management": "water treatment",
    "waste treatment": "wastewater treatment",
    "sewage treatment": "wastewater treatment",
    "building construction": "construction management",
    "construction site": "construction management",
    "site supervision": "site supervision",
    "gps": "gps surveying",
    "surveying instruments": "surveying",
    "total station": "total station",
    "autocad design": "autocad",
    "revit design": "revit",
    "revit modeling": "revit",
    "bim modeling": "bim (building information modeling)",
    "building information": "bim (building information modeling)",
    "quantity surveying": "cost estimation",
    "material testing": "material testing",
    "concrete testing": "concrete technology",
    
    # ──── ELECTRICAL ENGINEERING ────
    "dsp": "digital signal processing",
    "dsp processing": "digital signal processing",
    "signal proc": "digital signal processing",
    "emw": "electromagnetic waves",
    "em waves": "electromagnetic waves",
    "em field": "electromagnetics",
    "emc": "electromagnetic compatibility",
    "emc testing": "electromagnetic compatibility",
    "pid": "pid controller",
    "pid control": "pid controller",
    "iot devices": "iot",
    "internet things": "iot",
    "vlsi design": "vlsi",
    "vlsi": "vlsi",
    "asic design": "asic",
    "asic": "asic",
    "fpga programming": "fpga",
    "fpga": "fpga",
    "power generation": "power generation",
    "power transmission": "power transmission",
    "distribution system": "power distribution",
    "relay": "protection systems",
    "circuit breaker": "circuit breakers",
    "switchgear design": "switchgear",
    "scada system": "scada (supervisory control and data acquisition)",
    "control programming": "control systems",
    "plc programming": "plc (programmable logic controller)",
    "automation control": "automation",
    "load flow": "load flow analysis",
    "short circuit": "short circuit analysis",
    "stability": "stability analysis",
    "transformer": "transformer design",
    "motor": "motor design",
    "generator": "generator design",
    "converter": "converter design",
    "inverter": "inverter design",
    "power supply design": "power supply",
    "high voltage": "high voltage engineering",
    
    # ──── AEROSPACE ENGINEERING ────
    "aircraft design": "aircraft design",
    "aircraft struct": "structural analysis for aircraft",
    "fatigue": "fatigue analysis",
    "crack": "fracture mechanics",
    "flight mechanics": "flight mechanics",
    "aerodynamic": "aerodynamics",
    "propulsion": "propulsion systems",
    "jet engine": "jet engine design",
    "rocket engine": "rocket engine design",
    "avionics system": "avionics",
    "autopilot": "autopilot",
    "flight control": "flight control systems",
    "navigation system": "navigation systems",
    "aircraft maint": "aircraft maintenance",
    "aircraft systems": "aircraft systems",
    "hydraulic systems": "hydraulic systems",
    "aircraft hydraulic": "hydraulic systems",
    "composite": "composite materials",
    "titanium alloy": "titanium alloys",
    "aluminum alloy": "aluminum alloys",
    "aircraft manufacturing": "aircraft manufacturing",
    "aircraft assembly": "assembly processes",
    "aircraft quality": "quality control in aviation",
    "uav design": "uav design",
    "drone design": "drone design",
    "quadrotor": "quadrotor",
    "path planning": "path planning",
    "computer vision": "computer vision",
    
    # ──── CHEMICAL ENGINEERING ────
    "process engineering": "chemical processes",
    "reactor": "reactor design",
    "mass transfer": "mass transfer",
    "heat transfer": "heat transfer",
    "chemical process": "chemical processes",
    "process design": "process design",
    "distillation": "distillation",
    "separation": "separation processes",
    "crystallization": "crystallization",
    "agitation": "industrial mixing",
    "pharmacokinetics": "pharmaceutical engineering",
    "pharma manufacturing": "pharmaceutical engineering",
    "gmp compliance": "gmp (good manufacturing practice)",
    "drug manufacturing": "drug manufacturing",
    "food processing": "food processing",
    "food safety": "food safety",
    "food science": "food science",
    "waste management": "hazardous waste management",
    "environmental remediation": "environmental remediation",
    "pollution control": "air pollution control",
    "air treatment": "air pollution control",
    "water purification": "water purification",
    "psm": "psm (process safety management)",
    "hazop": "hazop analysis",
    "sop": "standard operating procedures",
    "safety management": "process safety",
    "plant control": "plant automation",
    "process automation": "plant automation",
    "spectroscopy analysis": "spectroscopy",
    "chromatography": "chromatography",
    "analytical chemistry": "chemical analysis",
    "troubleshooting": "troubleshooting",
    "optimization": "optimization",
    
    # ──── BIOMEDICAL ENGINEERING ────
    "device design": "medical device design",
    "biocompatibility": "biocompatibility",
    "tissue engineering": "tissue engineering",
    "biomechanical": "biomechanics",
    "orthopedic design": "orthopedic engineering",
    "cardiac device": "cardiac engineering",
    "clinical": "clinical engineering",
    "hospital equipment": "hospital equipment",
    "biomedical signal": "biomedical signals",
    "eeg signal": "eeg",
    "ecg signal": "ecg",
    "signal acquisition": "signal acquisition",
    "medical imaging": "medical imaging",
    "mri imaging": "mri",
    "ct imaging": "ct scan",
    "ultrasound": "ultrasound",
    "image processing": "image processing",
    "image reconstruction": "3d reconstruction",
    "bioinformatics": "bioinformatics",
    "genomics sequence": "genomics",
    "proteomics": "proteomics",
    "molecular biology": "molecular biology",
    "pharmaceutical": "pharmaceutical sciences",
    "drug formulation": "drug formulation",
    "toxicology": "toxicology",
    "fda": "regulatory compliance",
    "regulatory affair": "regulatory compliance",
    "clinical trials": "clinical trials",
    "telemedicine": "telemedicine",
    
    # ──── FINANCE & ACCOUNTING ────
    "gl accounting": "general ledger",
    "general ledger": "general ledger",
    "ap clerk": "accounts payable",
    "ar clerk": "accounts receivable",
    "journal entry": "journal entries",
    "balance sheet": "balance sheet",
    "pl statement": "income statement",
    "cash flow": "cash flow statement",
    "financial report": "financial reporting",
    "auditing": "audit",
    "internal audit": "internal audit",
    "external audit": "external audit",
    "ratio analysis": "ratio analysis",
    "financial ratio": "ratio analysis",
    "trend analysis": "trend analysis",
    "variance analysis": "variance analysis",
    "budget": "budgeting",
    "forecast": "forecasting",
    "cost accounting": "cost accounting",
    "cost allocation": "cost allocation",
    "cost control": "cost control",
    "cost reduction": "cost reduction",
    "tax planning": "tax accounting",
    "gst": "gst",
    "vat": "accounting",
    "sales tax": "sales tax",
    "financial modeling": "financial modeling",
    "valuation model": "valuation",
    "dcf": "dcf analysis",
    "sensitivity analysis": "sensitivity analysis",
    "portfolio": "portfolio management",
    "risk management": "risk management",
    "options trading": "options",
    "futures trading": "futures",
    "swing trading": "swaps",
    "credit risk": "credit analysis",
    "lending": "lending",
    "banking": "banking",
    "commercial bank": "commercial banking",
    "investment bank": "investment banking",
    "corporate finance": "corporate finance",
    "mergers": "mergers and acquisitions",
    "m&a": "mergers and acquisitions",
    "financial due diligence": "financial due diligence",
    "treasury": "treasury management",
    "working capital": "working capital management",
    "financial planner": "financial planning",
    "insurance": "insurance",
    "underwriting": "underwriting",
    "claims": "claims management",
    "sap finance": "sap",
    "oracle finance": "oracle financials",
    "quickbooks": "quickbooks",
    "xero accounting": "xero",
    "tally erp": "tally",
    "ms excel": "ms excel",
    "excel vba": "vba",
    "pivot tables": "pivot tables",
    "tds": "tds",
    "gratuity": "gratuity",
    "provident fund": "provident fund",
    "esop": "esop",
    
    # ──── HUMAN RESOURCES ────
    "talent acquisition": "recruiting",
    "recruitment": "recruiting",
    "sourcing": "candidate sourcing",
    "resume screening": "resume screening",
    "job posting": "job posting",
    "behavioral interview": "behavioral interviewing",
    "competency assessment": "competency assessment",
    "psychometric test": "psychometric testing",
    "onboarding": "onboarding",
    "employee orientation": "employee orientation",
    "induction training": "induction training",
    "performance appraisal": "performance appraisal",
    "performance planning": "performance planning",
    "objective setting": "goal setting",
    "okr": "okr (objectives and key results)",
    "kpi management": "kpia",
    "compensation planning": "salary planning",
    "salary planning": "salary planning",
    "benefits": "benefits administration",
    "payroll processing": "payroll processing",
    "tds management": "statutory compliance",
    "pf": "provident fund",
    "employee relations": "employee relations",
    "conflict resolution": "conflict resolution",
    "grievance": "grievance handling",
    "labor law": "labor law",
    "employment law": "employment law",
    "training design": "training and development",
    "corporate training": "corporate training",
    "coaching": "coaching",
    "mentoring": "mentoring",
    "succession": "succession planning",
    "org development": "organizational development",
    "change management": "change management",
    "culture building": "culture building",
    "engagement": "employee engagement",
    "survey analysis": "survey analysis",
    "feedback": "feedback management",
    "wellness": "wellness programs",
    "hr analytics": "hr analytics",
    "hris": "hr systems",
    "erp": "erp",
    "workday": "workday",
    "sap hr": "sap hr",
    "diversity": "diversity and inclusion",
    
    # ──── MARKETING ────
    "content strategy": "content marketing",
    "content creation": "content marketing",
    "blogging": "blogging",
    "copywriting": "copywriting",
    "search engine optimization": "seo (search engine optimization)",
    "search marketing": "sem (search engine marketing)",
    "google adwords": "ppc (pay-per-click)",
    "pay per click": "ppc (pay-per-click)",
    "social media": "social media marketing",
    "facebook marketing": "facebook",
    "instagram marketing": "instagram",
    "twitter marketing": "twitter",
    "linkedin marketing": "linkedin",
    "youtube marketing": "youtube",
    "community manager": "community management",
    "brand strategy": "brand strategy",
    "branding": "brand management",
    "digital": "digital marketing",
    "web analytics": "web analytics",
    "google analytics": "google analytics",
    "marketing automation": "marketing automation",
    "crm": "customer relationship management",
    "email campaign": "email marketing",
    "marketing research": "market research",
    "consumer research": "consumer research",
    "competitive analysis": "competitive analysis",
    "product positioning": "product positioning",
    "market segmentation": "market segmentation",
    "customer journey": "customer journey",
    "cro": "conversion rate optimization",
    "ab testing": "a/b testing",
    "user testing": "user experience testing",
    "marketing metrics": "marketing metrics",
    "roi": "roi",
    "cac": "customer acquisition cost",
    "customer lifetime": "customer lifetime value",
    "retention": "retention marketing",
    "loyalty program": "customer loyalty",
    "influencer": "influencer marketing",
    "viral": "viral marketing",
    "event marketing": "event marketing",
    "public relations": "pr (public relations)",
    "media relations": "media relations",
    "crisis": "crisis management",
    "reputation": "reputation management",
    "print advertising": "print advertising",
    "outdoor advertising": "outdoor advertising",
    "affiliate": "affiliate marketing",
    "referral": "referral marketing",
    "video marketing": "video marketing",
    "ar marketing": "augmented reality",
    
    # ──── OPERATIONS ────
    "supply chain": "supply chain management",
    "procurement": "procurement",
    "vendor management": "vendor management",
    "logistics": "logistics",
    "warehouse": "warehouse management",
    "inventory": "inventory management",
    "demand planning": "demand planning",
    "production planning": "production planning",
    "scheduling": "scheduling",
    "capacity planning": "capacity planning",
    "quality": "quality management",
    "process improvement": "business process improvement",
    "lean": "lean management",
    "six sigma": "six sigma",
    "kaizen": "kaizen",
    "optimization": "process optimization",
    "risk": "risk management",
    "business continuity": "business continuity",
    "disaster recovery": "disaster recovery",
    "kpi": "kpi tracking",
    "analytics": "analytics",
    "performance monitoring": "performance monitoring",
    "inventory modeling": "inventory modeling",
    "just in time": "just-in-time",
    "kanban": "kanban",
    
    # ──── SALES ────
    "sales exec": "sales management",
    "sales manager": "sales management",
    "account exec": "account management",
    "key account": "key account management",
    "client management": "client relationship",
    "pipeline": "pipeline management",
    "deal closure": "deal closure",
    "negotiation skill": "negotiation",
    "contract": "contract negotiation",
    "customer acquisition": "customer acquisition",
    "customer retention": "customer retention",
    "customer service": "customer service",
    "sales forecast": "sales forecasting",
    "revenue forecast": "revenue forecasting",
    "sales projection": "sales projection",
    "competitive intel": "competitive intelligence",
    "sales enablement": "sales enablement",
    "sales training": "sales training",
    "sales coaching": "sales coaching",
    "salesforce": "salesforce",
    "sales tool": "sales tool",
    "sales process": "sales process",
    "presentation": "presentation skills",
    "communication": "communication",
    "listening skill": "listening skills",
    "product knowledge": "product knowledge",
    "pricing strategy": "pricing",
    "discount strategy": "discount strategy",
    "margin management": "margin management",
    "lead generation": "lead generation",
    "lead qualification": "lead qualification",
    "lead management": "sales funnel",
    "prospecting": "prospecting",
    "networking": "networking",
    "inside sales": "inside sales",
    "field sales": "field sales",
    "remote sales": "remote sales",
    
    # ──── PRODUCT MANAGEMENT ────
    "product road map": "product roadmap",
    "feature planning": "product planning",
    "requirements": "product requirements",
    "ux design": "user research",
    "ui design": "ui",
    "user experience": "ux",
    "wireframe": "wireframing",
    "prototype": "prototyping",
    "usability testing": "user testing",
    "persona": "user research",
    "market": "market analysis",
    "go to market": "go-to-market strategy",
    "product launch": "launch planning",
    "product vision": "product vision",
    "stakeholder management": "stakeholder management",
    "metrics": "metrics and analytics",
    "product metrics": "product metrics",
    "engagement": "user engagement metrics",
    "experimentation": "experimentation",
    "data driven": "data-driven decision making",
    "feedback": "customer feedback",
    "priortization": "product prioritization",
    "agile pm": "agile",
    
    # ──── PROJECT MANAGEMENT ────
    "project manager": "project management",
    "project planning": "project planning",
    "project scope": "project scope",
    "wbs": "work breakdown structure",
    "schedule management": "schedule management",
    "timeline management": "timeline",
    "critical path": "critical path",
    "gantt chart": "gantt charts",
    "resource planning": "resource planning",
    "resource management": "resource allocation",
    "budget planning": "budget management",
    "cost estimate": "cost estimation",
    "cost management": "cost control",
    "cost tracking": "cost tracking",
    "risk planning": "risk management",
    "risk assessment": "risk assessment",
    "quality planning": "quality planning",
    "quality assurance": "quality assurance",
    "quality control": "quality control",
    "stakeholder management": "stakeholder management",
    "communication planning": "communication planning",
    "procurement planning": "procurement",
    "vendor selection": "vendor selection",
    "scope management": "scope management",
    "change management": "change management",
    "baseline": "baseline management",
    "evm": "earned value management",
    "performance tracking": "performance tracking",
    "issue tracking": "issue tracking",
    "meeting management": "meeting management",
    "documentation": "documentation",
    "scrum master": "scrum",
    "kanban": "kanban",
    "xp": "xp",
    "ms project": "ms project",
    "jira": "jira",
    "asana": "asana",
    "monday": "monday.com",
    "leadership": "team leadership",
    
    # ──── DESIGN ────
    "graphic": "graphic design",
    "visual": "visual design",
    "logo": "logo design",
    "fonts": "typography",
    "color theory": "color theory",
    "composition": "composition",
    "photo": "photography",
    "image editing": "image editing",
    "print": "print design",
    "packaging": "packaging design",
    "web design": "web design",
    "responsive": "responsive design",
    "mobile design": "mobile design",
    "accessibility": "accessibility",
    "animation": "animation",
    "motion design": "motion design",
    "video production": "video production",
    "photoshop": "photoshop",
    "illustrator": "illustrator",
    "indesign": "indesign",
    "figma": "figma",
    "sketch": "sketch",
    "xd": "xd",
    "blender": "blender",
    "unity 3d": "unity",
    
    # ──── BUSINESS ANALYSIS ────
    "ba": "business analysis",
    "requirements": "requirements analysis",
    "business process": "business process improvement",
    "process mapping": "process mapping",
    "gap analysis": "gap analysis",
    "feasibility": "feasibility analysis",
    "swot": "swot analysis",
    "bi": "business intelligence",
    "data analytics": "analytics",
    "dashboards": "dashboard",
    "reporting": "reporting",
    "technical writing": "technical writing",
    "documentation": "documentation",
    "strategy": "strategic planning",
    "strategic planning": "strategic planning",
    "vision": "vision setting",
    "leadership": "leadership",
    "team lead": "team management",
    "communication": "communication",
    "public speaker": "public speaking",
    "persuasion": "persuasion",
    "interpersonal": "interpersonal skills",
    "critical thinking": "critical thinking",
    "problem solving": "problem solving",
    "creativity": "creativity",
    "innovation": "innovation",
    "coaching": "coaching and mentoring",
    "mentoring": "mentoring",
}

# ── Deduplication groups (keep canonical form) ─────────────────────────
SKILL_DEDUP_GROUPS = {
    "java": ["core java", "java programming", "java se", "java ee"],
    "python": ["python3", "python 3", "python programming", "cpython"],
    "javascript": ["js", "ecmascript", "es6"],
    "machine learning": ["ml", "machine-learning"],
    "deep learning": ["dl", "deep-learning"],
    "natural language processing": ["nlp", "text mining"],
    "docker": ["docker containers", "dockerized"],
    "kubernetes": ["k8s", "kube"],
    "sql": ["structured query language"],
    "rest api": ["restful api", "rest apis", "restful", "restapi"],
    "ci/cd": ["ci cd", "cicd", "continuous integration"],
    "react": ["reactjs", "react.js"],
    "node.js": ["nodejs", "node"],
    "angular": ["angularjs", "angular.js"],
    "vue": ["vuejs", "vue.js"],
    "tensorflow": ["tf", "tensor-flow"],
    "pytorch": ["py-torch"],
}

# ── Experience-level keywords ──────────────────────────────────────────
EXPERIENCE_KEYWORDS = {
    "entry": ["entry level", "junior", "intern", "fresh", "0-1 year", "0-2 year"],
    "mid": ["mid level", "2-5 year", "3-5 year", "2+ year", "3+ year"],
    "senior": ["senior", "lead", "5+ year", "7+ year", "principal", "staff"],
    "executive": ["director", "vp", "cto", "cio", "head of", "10+ year"],
}

# ── Proficiency keywords ──────────────────────────────────────────────
PROFICIENCY_KEYWORDS = {
    "advanced": [
        "expert", "advanced", "proficient", "extensive experience",
        "deep knowledge", "mastery", "specialist", "5+ years",
    ],
    "intermediate": [
        "intermediate", "working knowledge", "competent",
        "familiar", "hands-on", "2+ years", "3+ years",
    ],
    "basic": [
        "basic", "beginner", "novice", "exposure", "introductory",
        "coursework", "academic", "learning",
    ],
}
