"""
Comprehensive Job Role Database
================================
Covers 200+ job roles across all major industries and domains.
Each role maps to relevant skills for accurate job matching.
"""

COMPREHENSIVE_JOB_DATABASE = [
    {
        "role": "Frontend Developer",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["javascript", "html", "css", "react", "typescript"],
        "optional_skills": ["vue", "angular", "next.js", "tailwind", "sass", "webpack", "vite", "svelte", "figma", "jest", "cypress", "graphql", "redux", "material-ui", "bootstrap"],
    },
    {
        "role": "Backend Developer",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["python", "java", "node.js", "sql", "rest api"],
        "optional_skills": ["django", "flask", "fastapi", "spring boot", "express", "postgresql", "mongodb", "redis", "docker", "graphql", "rabbitmq", "celery", "microservices", "linux", "mysql", "orm", "authentication", "jwt"],
    },
    {
        "role": "Full Stack Developer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["javascript", "python", "react", "node.js", "sql"],
        "optional_skills": ["typescript", "html", "css", "django", "flask", "fastapi", "next.js", "mongodb", "postgresql", "docker", "git", "rest api", "graphql", "tailwind", "express", "aws", "ci/cd", "redis"],
    },
    {
        "role": "Mobile App Developer (Android)",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["android", "kotlin", "java", "android studio"],
        "optional_skills": ["jetpack compose", "mvvm", "room", "retrofit", "firebase", "rest api", "xml", "gradle", "material design", "coroutines", "dagger", "hilt"],
    },
    {
        "role": "Mobile App Developer (iOS)",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["ios", "swift", "xcode"],
        "optional_skills": ["swiftui", "uikit", "core data", "firebase", "rest api", "cocoapods", "carthage", "combine", "objective-c", "mvvm"],
    },
    {
        "role": "Mobile App Developer (Cross-Platform)",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["flutter", "dart", "react native"],
        "optional_skills": ["javascript", "typescript", "firebase", "rest api", "state management", "redux", "bloc", "provider", "expo"],
    },
    {
        "role": "DevOps Engineer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["docker", "kubernetes", "ci/cd", "linux", "aws"],
        "optional_skills": ["terraform", "ansible", "jenkins", "github actions", "gitlab ci", "azure", "gcp", "helm", "prometheus", "grafana", "nginx", "elk stack", "istio", "cloudformation", "pulumi", "shell scripting", "python", "monitoring"],
    },
    {
        "role": "Cloud Engineer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["aws", "azure", "gcp", "cloud computing", "linux"],
        "optional_skills": ["docker", "kubernetes", "terraform", "cloudformation", "lambda", "s3", "ec2", "iam", "vpc", "cloud security", "serverless", "microservices"],
    },
    {
        "role": "Site Reliability Engineer (SRE)",
        "domain": "Software Engineering",
        "level": "Senior",
        "core_skills": ["linux", "docker", "kubernetes", "python", "monitoring"],
        "optional_skills": ["prometheus", "grafana", "terraform", "ansible", "ci/cd", "aws", "distributed systems", "incident response", "on-call", "shell scripting"],
    },
    {
        "role": "Database Administrator (DBA)",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["sql", "postgresql", "mysql", "database administration"],
        "optional_skills": ["oracle", "sql server", "mongodb", "redis", "backup recovery", "performance tuning", "replication", "data modeling", "indexing"],
    },
    {
        "role": "Software Architect",
        "domain": "Software Engineering",
        "level": "Senior/Lead",
        "core_skills": ["system design", "architecture patterns", "microservices", "distributed systems"],
        "optional_skills": ["docker", "kubernetes", "aws", "design patterns", "scalability", "rest api", "graphql", "event-driven", "caching", "load balancing"],
    },
    {
        "role": "Game Developer",
        "domain": "Software Engineering",
        "level": "Entry to Senior",
        "core_skills": ["unity", "unreal engine", "c#", "c++"],
        "optional_skills": ["3d modeling", "animation", "physics", "game design", "blender", "shader programming", "multiplayer networking"],
    },
    {
        "role": "Blockchain Developer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["blockchain", "solidity", "ethereum", "smart contracts"],
        "optional_skills": ["web3", "truffle", "hardhat", "javascript", "cryptography", "defi", "nft", "rust", "hyperledger"],
    },
    {
        "role": "API Developer",
        "domain": "Software Engineering",
        "level": "Entry to Mid",
        "core_skills": ["rest api", "python", "node.js", "api design"],
        "optional_skills": ["graphql", "fastapi", "express", "swagger", "postman", "authentication", "rate limiting", "microservices"],
    },
    {
        "role": "Systems Programmer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["c", "c++", "linux", "operating systems"],
        "optional_skills": ["assembly", "rust", "go", "kernel development", "device drivers", "system calls", "memory management", "concurrency"],
    },
    {
        "role": "Embedded Software Engineer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["c", "embedded c", "microcontroller", "rtos"],
        "optional_skills": ["c++", "arm", "stm32", "embedded linux", "device drivers", "i2c", "spi", "uart", "debugging"],
    },
    {
        "role": "Test Automation Engineer",
        "domain": "Software Engineering",
        "level": "Entry to Mid",
        "core_skills": ["selenium", "python", "test automation"],
        "optional_skills": ["cypress", "playwright", "jest", "pytest", "junit", "jenkins", "ci/cd", "jira", "postman", "robot framework"],
    },
    {
        "role": "QA Engineer",
        "domain": "Software Engineering",
        "level": "Entry to Mid",
        "core_skills": ["manual testing", "test cases", "bug tracking"],
        "optional_skills": ["selenium", "jira", "postman", "api testing", "regression testing", "agile", "test planning"],
    },
    {
        "role": "Security Engineer",
        "domain": "Software Engineering",
        "level": "Mid to Senior",
        "core_skills": ["cybersecurity", "linux", "networking", "python"],
        "optional_skills": ["penetration testing", "vulnerability assessment", "owasp", "encryption", "firewall", "ids/ips", "security auditing", "incident response"],
    },
    {
        "role": "Penetration Tester / Ethical Hacker",
        "domain": "Cybersecurity",
        "level": "Mid to Senior",
        "core_skills": ["penetration testing", "linux", "networking", "python"],
        "optional_skills": ["metasploit", "burp suite", "wireshark", "nmap", "owasp", "web application security", "bash", "kali linux"],
    },
    {
        "role": "Data Scientist",
        "domain": "Data Science",
        "level": "Mid to Senior",
        "core_skills": ["python", "machine learning", "statistics", "pandas", "data analysis"],
        "optional_skills": ["scikit-learn", "numpy", "scipy", "matplotlib", "seaborn", "tableau", "power bi", "r", "sql", "deep learning", "nlp", "time series", "feature engineering", "jupyter", "data visualization"],
    },
    {
        "role": "Data Analyst",
        "domain": "Data Science",
        "level": "Entry to Mid",
        "core_skills": ["sql", "data analysis", "excel", "data visualization"],
        "optional_skills": ["python", "r", "tableau", "power bi", "pandas", "statistics", "looker", "google analytics", "business intelligence"],
    },
    {
        "role": "Business Analyst",
        "domain": "Data Science",
        "level": "Entry to Mid",
        "core_skills": ["data analysis", "excel", "sql", "business intelligence"],
        "optional_skills": ["tableau", "power bi", "python", "jira", "agile", "requirements gathering", "stakeholder management", "process improvement"],
    },
    {
        "role": "Data Engineer",
        "domain": "Data Engineering",
        "level": "Mid to Senior",
        "core_skills": ["python", "sql", "etl", "data pipeline", "spark"],
        "optional_skills": ["hadoop", "kafka", "airflow", "snowflake", "dbt", "aws", "gcp", "big data", "data warehouse", "databricks", "data modeling", "prefect", "dagster", "docker", "postgresql"],
    },
    {
        "role": "Analytics Engineer",
        "domain": "Data Engineering",
        "level": "Mid",
        "core_skills": ["sql", "dbt", "data modeling", "python"],
        "optional_skills": ["snowflake", "bigquery", "looker", "tableau", "airflow", "git", "data warehouse"],
    },
    {
        "role": "Business Intelligence Engineer",
        "domain": "Data Science",
        "level": "Mid",
        "core_skills": ["sql", "tableau", "power bi", "data visualization"],
        "optional_skills": ["python", "etl", "data modeling", "dashboards", "looker", "excel", "data warehouse"],
    },
    {
        "role": "Quantitative Analyst",
        "domain": "Finance/Data",
        "level": "Senior",
        "core_skills": ["python", "statistics", "mathematics", "finance"],
        "optional_skills": ["r", "matlab", "machine learning", "time series", "derivatives", "risk modeling", "portfolio optimization"],
    },
    {
        "role": "Research Analyst",
        "domain": "Research",
        "level": "Entry to Mid",
        "core_skills": ["research", "data analysis", "excel", "presentation"],
        "optional_skills": ["python", "r", "sql", "statistics", "report writing", "data visualization"],
    },
    {
        "role": "Marketing Analyst",
        "domain": "Marketing/Data",
        "level": "Entry to Mid",
        "core_skills": ["data analysis", "excel", "google analytics", "marketing"],
        "optional_skills": ["sql", "python", "tableau", "a/b testing", "customer segmentation", "seo", "sem"],
    },
    {
        "role": "Product Analyst",
        "domain": "Product/Data",
        "level": "Mid",
        "core_skills": ["data analysis", "sql", "product metrics", "analytics"],
        "optional_skills": ["python", "tableau", "a/b testing", "user research", "mixpanel", "amplitude", "product management"],
    },
    {
        "role": "Financial Analyst",
        "domain": "Finance",
        "level": "Entry to Mid",
        "core_skills": ["excel", "financial modeling", "accounting", "finance"],
        "optional_skills": ["python", "sql", "tableau", "power bi", "valuation", "budgeting", "forecasting"],
    },
    {
        "role": "Risk Analyst",
        "domain": "Finance/Data",
        "level": "Mid",
        "core_skills": ["risk management", "statistics", "excel", "data analysis"],
        "optional_skills": ["python", "r", "sql", "monte carlo simulation", "credit risk", "market risk"],
    },
    {
        "role": "Data Quality Analyst",
        "domain": "Data Engineering",
        "level": "Entry to Mid",
        "core_skills": ["sql", "data quality", "data validation"],
        "optional_skills": ["python", "etl", "data profiling", "data governance", "great expectations"],
    },
    {
        "role": "Machine Learning Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "machine learning", "tensorflow", "pytorch", "scikit-learn"],
        "optional_skills": ["deep learning", "neural networks", "nlp", "computer vision", "feature engineering", "model deployment", "mlops", "docker", "numpy", "pandas", "xgboost", "lightgbm", "onnx", "tensorrt", "statistics", "aws", "kubernetes"],
    },
    {
        "role": "AI Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "deep learning", "machine learning", "neural networks"],
        "optional_skills": ["tensorflow", "pytorch", "transformers", "nlp", "computer vision", "reinforcement learning", "mlops", "model deployment"],
    },
    {
        "role": "Generative AI Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "llm", "langchain", "generative ai", "transformers"],
        "optional_skills": ["rag", "hugging face", "openai", "prompt engineering", "fine-tuning", "vector database", "chromadb", "pinecone", "llamaindex", "ollama", "groq", "vllm", "pytorch", "tensorflow", "fastapi", "streamlit"],
    },
    {
        "role": "LLM Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "llm", "transformers", "langchain"],
        "optional_skills": ["openai", "hugging face", "prompt engineering", "fine-tuning", "rag", "vector database", "llamaindex", "pytorch"],
    },
    {
        "role": "MLOps Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "docker", "kubernetes", "machine learning", "mlops"],
        "optional_skills": ["mlflow", "kubeflow", "tensorflow", "pytorch", "ci/cd", "model monitoring", "aws", "azure ml", "sagemaker"],
    },
    {
        "role": "Computer Vision Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "computer vision", "opencv", "deep learning", "image processing"],
        "optional_skills": ["pytorch", "tensorflow", "yolo", "object detection", "image classification", "cnn", "segmentation", "numpy", "transfer learning"],
    },
    {
        "role": "NLP Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "nlp", "natural language processing", "transformers", "deep learning"],
        "optional_skills": ["bert", "gpt", "hugging face", "text classification", "named entity recognition", "sentiment analysis", "pytorch", "tensorflow", "llm", "langchain", "spacy"],
    },
    {
        "role": "Deep Learning Engineer",
        "domain": "AI/ML",
        "level": "Senior",
        "core_skills": ["python", "deep learning", "neural networks", "pytorch", "tensorflow"],
        "optional_skills": ["cnn", "rnn", "lstm", "gru", "transformers", "computer vision", "nlp", "model optimization", "gpu programming"],
    },
    {
        "role": "Research Scientist (AI)",
        "domain": "Research/AI",
        "level": "Senior/PhD",
        "core_skills": ["python", "machine learning", "deep learning", "research", "mathematics"],
        "optional_skills": ["pytorch", "tensorflow", "nlp", "computer vision", "reinforcement learning", "paper writing", "experimentation"],
    },
    {
        "role": "AI Product Manager",
        "domain": "Product/AI",
        "level": "Mid to Senior",
        "core_skills": ["product management", "machine learning", "ai strategy"],
        "optional_skills": ["python", "data analysis", "stakeholder management", "roadmapping", "agile", "user research"],
    },
    {
        "role": "Prompt Engineer",
        "domain": "AI/ML",
        "level": "Entry to Mid",
        "core_skills": ["prompt engineering", "llm", "chatgpt", "ai"],
        "optional_skills": ["python", "langchain", "openai api", "natural language", "testing", "optimization"],
    },
    {
        "role": "Reinforcement Learning Engineer",
        "domain": "AI/ML",
        "level": "Senior",
        "core_skills": ["python", "reinforcement learning", "deep learning", "pytorch"],
        "optional_skills": ["gym", "rl algorithms", "q-learning", "policy gradient", "robotics", "game ai"],
    },
    {
        "role": "Speech Recognition Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "speech recognition", "audio processing", "deep learning"],
        "optional_skills": ["pytorch", "tensorflow", "asr", "tts", "wav2vec", "whisper", "signal processing"],
    },
    {
        "role": "Recommendation Systems Engineer",
        "domain": "AI/ML",
        "level": "Mid to Senior",
        "core_skills": ["python", "machine learning", "recommendation systems", "collaborative filtering"],
        "optional_skills": ["tensorflow", "pytorch", "matrix factorization", "deep learning", "ranking", "personalization"],
    },
    {
        "role": "Time Series Analyst",
        "domain": "Data Science/AI",
        "level": "Mid",
        "core_skills": ["python", "time series", "statistics", "forecasting"],
        "optional_skills": ["arima", "prophet", "lstm", "pandas", "scikit-learn", "r"],
    },
    {
        "role": "VLSI Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["vhdl", "verilog", "fpga", "vlsi", "digital design"],
        "optional_skills": ["systemverilog", "asic", "cadence", "synopsys", "xilinx", "vivado", "quartus", "modelsim", "spice", "ltspice", "soc", "rtl design", "cpld"],
    },
    {
        "role": "FPGA Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["fpga", "vhdl", "verilog", "digital design"],
        "optional_skills": ["xilinx", "altera", "vivado", "quartus", "systemverilog", "timing analysis", "synthesis"],
    },
    {
        "role": "ASIC Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Senior",
        "core_skills": ["verilog", "systemverilog", "asic", "vlsi"],
        "optional_skills": ["rtl design", "synthesis", "timing analysis", "cadence", "synopsys", "physical design"],
    },
    {
        "role": "Verification Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["systemverilog", "uvm", "verification", "vhdl"],
        "optional_skills": ["verilog", "testbench", "assertions", "coverage", "simulation", "modelsim"],
    },
    {
        "role": "Physical Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Senior",
        "core_skills": ["physical design", "vlsi", "asic", "placement and routing"],
        "optional_skills": ["cadence", "synopsys", "timing closure", "power analysis", "drc", "lvs"],
    },
    {
        "role": "Embedded Systems Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["embedded systems", "c", "microcontroller", "rtos"],
        "optional_skills": ["embedded c", "c++", "arm", "stm32", "8051", "avr", "arduino", "raspberry pi", "esp32", "firmware", "i2c", "spi", "uart", "can bus", "pcb design", "linux", "assembly"],
    },
    {
        "role": "Firmware Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["c", "firmware", "microcontroller", "embedded systems"],
        "optional_skills": ["c++", "rtos", "arm", "device drivers", "communication protocols", "debugging"],
    },
    {
        "role": "PCB Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid",
        "core_skills": ["pcb design", "circuit design", "altium", "eagle"],
        "optional_skills": ["kicad", "orcad", "analog circuits", "digital circuits", "signal integrity", "emi/emc", "multilayer pcb"],
    },
    {
        "role": "Hardware Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["circuit design", "pcb design", "analog circuits", "digital circuits"],
        "optional_skills": ["altium", "eagle", "kicad", "ltspice", "oscilloscope", "multimeter", "soldering", "prototyping", "signal conditioning", "adc", "dac", "power electronics", "schematic design"],
    },
    {
        "role": "Analog Design Engineer",
        "domain": "Electrical Engineering",
        "level": "Senior",
        "core_skills": ["analog circuits", "circuit design", "ltspice", "spice"],
        "optional_skills": ["amplifier design", "filter design", "adc", "dac", "power electronics", "pcb design"],
    },
    {
        "role": "Power Electronics Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["power electronics", "circuit design", "power systems"],
        "optional_skills": ["dc-dc converter", "inverter", "rectifier", "smps", "motor drives", "matlab", "simulink", "ltspice"],
    },
    {
        "role": "Signal Processing Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["digital signal processing", "matlab", "signal processing", "algorithms"],
        "optional_skills": ["fourier transform", "fft", "wavelet transform", "z transform", "laplace transform", "simulink", "python", "numpy", "scipy", "image processing", "audio processing", "communication systems"],
    },
    {
        "role": "RF Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["rf engineering", "antenna design", "wireless communication", "electromagnetics"],
        "optional_skills": ["5g", "lte", "microwave", "circuit design", "matlab", "hfss", "cst", "smith chart"],
    },
    {
        "role": "Telecommunications Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["telecommunications", "communication systems", "networking"],
        "optional_skills": ["rf engineering", "fiber optics", "5g", "lte", "wireless communication", "antenna design", "matlab"],
    },
    {
        "role": "Control Systems Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["control systems", "matlab", "simulink", "pid controller"],
        "optional_skills": ["pid", "motor control", "plc", "scada", "industrial automation", "labview", "python", "state space", "transfer functions"],
    },
    {
        "role": "Automation Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid",
        "core_skills": ["plc", "scada", "automation", "industrial control"],
        "optional_skills": ["hmi", "ladder logic", "siemens", "allen bradley", "sensors", "actuators", "labview"],
    },
    {
        "role": "Power Systems Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["power systems", "electric machines", "power electronics"],
        "optional_skills": ["renewable energy", "solar energy", "wind energy", "grid integration", "transformers", "matlab", "simulink", "etap"],
    },
    {
        "role": "Test Engineer (Hardware)",
        "domain": "Electrical Engineering",
        "level": "Entry to Mid",
        "core_skills": ["hardware testing", "test automation", "oscilloscope", "multimeter"],
        "optional_skills": ["labview", "python", "circuit debugging", "functional testing", "signal analysis"],
    },
    {
        "role": "Field Application Engineer",
        "domain": "Electrical Engineering",
        "level": "Mid",
        "core_skills": ["customer support", "technical sales", "embedded systems"],
        "optional_skills": ["circuit design", "troubleshooting", "communication", "presentation"],
    },
    {
        "role": "Mechanical Design Engineer",
        "domain": "Mechanical Engineering",
        "level": "Entry to Senior",
        "core_skills": ["solidworks", "autocad", "mechanical design", "cad"],
        "optional_skills": ["catia", "creo", "inventor", "nx", "fusion 360", "gd&t", "3d modeling", "3d printing", "materials science", "manufacturing", "assembly design"],
    },
    {
        "role": "CAD Engineer",
        "domain": "Mechanical Engineering",
        "level": "Entry to Mid",
        "core_skills": ["autocad", "solidworks", "cad", "3d modeling"],
        "optional_skills": ["catia", "creo", "inventor", "technical drawing", "gd&t", "drafting"],
    },
    {
        "role": "Product Design Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["product design", "solidworks", "prototyping", "cad"],
        "optional_skills": ["industrial design", "3d printing", "materials selection", "dfm", "dfa"],
    },
    {
        "role": "FEA Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["ansys", "finite element analysis", "fea", "structural analysis"],
        "optional_skills": ["abaqus", "comsol", "solidworks simulation", "nastran", "ls-dyna", "stress analysis", "modal analysis"],
    },
    {
        "role": "CFD Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["cfd", "computational fluid dynamics", "ansys fluent", "fluid mechanics"],
        "optional_skills": ["openfoam", "star-ccm+", "heat transfer", "turbulence modeling", "meshing"],
    },
    {
        "role": "Simulation Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["ansys", "simulation", "fea", "cfd"],
        "optional_skills": ["abaqus", "comsol", "ls-dyna", "multiphysics", "optimization"],
    },
    {
        "role": "Manufacturing Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid",
        "core_skills": ["manufacturing", "cnc", "machining", "process improvement"],
        "optional_skills": ["lean manufacturing", "six sigma", "quality control", "cam", "3d printing", "welding", "assembly", "gd&t"],
    },
    {
        "role": "CNC Programmer",
        "domain": "Mechanical Engineering",
        "level": "Entry to Mid",
        "core_skills": ["cnc", "cnc programming", "g-code", "machining"],
        "optional_skills": ["cam", "mastercam", "solidcam", "lathe", "milling", "tooling"],
    },
    {
        "role": "Quality Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid",
        "core_skills": ["quality control", "six sigma", "inspection", "gd&t"],
        "optional_skills": ["lean manufacturing", "root cause analysis", "spc", "fmea", "metrology", "cmm"],
    },
    {
        "role": "HVAC Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["hvac", "thermodynamics", "heat transfer", "fluid mechanics"],
        "optional_skills": ["autocad", "revit", "hvac design", "ductwork", "load calculation", "refrigeration"],
    },
    {
        "role": "Piping Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["piping", "autocad", "piping design", "fluid mechanics"],
        "optional_skills": ["caesar ii", "pdms", "sp3d", "stress analysis", "p&id"],
    },
    {
        "role": "Automotive Engineer",
        "domain": "Mechanical/Automotive",
        "level": "Mid to Senior",
        "core_skills": ["automotive engineering", "cad", "vehicle dynamics"],
        "optional_skills": ["catia", "solidworks", "ansys", "matlab", "engine design", "electric vehicles", "crash analysis"],
    },
    {
        "role": "Thermal Engineer",
        "domain": "Mechanical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["heat transfer", "thermodynamics", "thermal analysis", "ansys"],
        "optional_skills": ["cfd", "cooling systems", "thermal management", "hvac"],
    },
    {
        "role": "Maintenance Engineer",
        "domain": "Mechanical Engineering",
        "level": "Entry to Mid",
        "core_skills": ["maintenance", "troubleshooting", "mechanical systems"],
        "optional_skills": ["preventive maintenance", "reliability", "plc", "hydraulics", "pneumatics"],
    },
    {
        "role": "Structural Engineer",
        "domain": "Civil Engineering",
        "level": "Mid to Senior",
        "core_skills": ["structural engineering", "staad pro", "etabs", "structural analysis"],
        "optional_skills": ["revit", "autocad", "sap2000", "concrete design", "steel design", "seismic design", "bim", "tekla"],
    },
    {
        "role": "Civil Engineer",
        "domain": "Civil Engineering",
        "level": "Entry to Senior",
        "core_skills": ["civil engineering", "autocad", "construction", "surveying"],
        "optional_skills": ["project management", "quantity surveying", "estimating", "site supervision", "concrete technology"],
    },
    {
        "role": "BIM Engineer",
        "domain": "Civil Engineering",
        "level": "Mid",
        "core_skills": ["bim", "revit", "autocad", "3d modeling"],
        "optional_skills": ["navisworks", "civil 3d", "coordination", "clash detection"],
    },
    {
        "role": "Quantity Surveyor",
        "domain": "Civil Engineering",
        "level": "Mid",
        "core_skills": ["quantity surveying", "cost estimation", "construction"],
        "optional_skills": ["autocad", "excel", "budgeting", "tendering", "contract management"],
    },
    {
        "role": "Geotechnical Engineer",
        "domain": "Civil Engineering",
        "level": "Mid to Senior",
        "core_skills": ["geotechnical engineering", "soil mechanics", "foundation design"],
        "optional_skills": ["plaxis", "slope stability", "retaining walls", "site investigation"],
    },
    {
        "role": "Transportation Engineer",
        "domain": "Civil Engineering",
        "level": "Mid to Senior",
        "core_skills": ["transportation engineering", "traffic engineering", "autocad"],
        "optional_skills": ["highway design", "traffic simulation", "civil 3d", "pavement design"],
    },
    {
        "role": "Water Resources Engineer",
        "domain": "Civil Engineering",
        "level": "Mid to Senior",
        "core_skills": ["water resources", "hydrology", "hydraulics"],
        "optional_skills": ["hec-ras", "swmm", "autocad", "flood modeling", "drainage design"],
    },
    {
        "role": "Construction Manager",
        "domain": "Civil Engineering",
        "level": "Senior",
        "core_skills": ["construction management", "project management", "scheduling"],
        "optional_skills": ["primavera", "ms project", "budgeting", "contracts", "safety management"],
    },
    {
        "role": "Site Engineer",
        "domain": "Civil Engineering",
        "level": "Entry to Mid",
        "core_skills": ["site supervision", "construction", "autocad", "surveying"],
        "optional_skills": ["quality control", "safety", "coordination", "material testing"],
    },
    {
        "role": "Environmental Engineer",
        "domain": "Civil/Environmental",
        "level": "Mid to Senior",
        "core_skills": ["environmental engineering", "water treatment", "waste management"],
        "optional_skills": ["gis", "environmental impact assessment", "air quality", "sustainability"],
    },
    {
        "role": "Aerospace Engineer",
        "domain": "Aerospace",
        "level": "Mid to Senior",
        "core_skills": ["aerospace engineering", "aerodynamics", "cfd", "matlab"],
        "optional_skills": ["catia", "solidworks", "ansys", "simulink", "propulsion", "flight dynamics", "stress analysis"],
    },
    {
        "role": "Aircraft Design Engineer",
        "domain": "Aerospace",
        "level": "Senior",
        "core_skills": ["aircraft design", "catia", "aerodynamics", "cad"],
        "optional_skills": ["solidworks", "nx", "stress analysis", "composites", "structural analysis"],
    },
    {
        "role": "Propulsion Engineer",
        "domain": "Aerospace",
        "level": "Senior",
        "core_skills": ["propulsion", "thermodynamics", "fluid mechanics", "cfd"],
        "optional_skills": ["rocket engines", "jet engines", "combustion", "matlab", "ansys"],
    },
    {
        "role": "Flight Dynamics Engineer",
        "domain": "Aerospace",
        "level": "Senior",
        "core_skills": ["flight dynamics", "control systems", "matlab", "simulink"],
        "optional_skills": ["autopilot", "guidance", "navigation", "uav"],
    },
    {
        "role": "Avionics Engineer",
        "domain": "Aerospace",
        "level": "Mid to Senior",
        "core_skills": ["avionics", "embedded systems", "communication systems"],
        "optional_skills": ["c", "c++", "flight control", "radar", "navigation systems"],
    },
    {
        "role": "UAV / Drone Engineer",
        "domain": "Aerospace/Robotics",
        "level": "Mid",
        "core_skills": ["uav", "drone", "flight control", "autopilot"],
        "optional_skills": ["pixhawk", "ardupilot", "computer vision", "embedded systems", "ros"],
    },
    {
        "role": "Space Systems Engineer",
        "domain": "Aerospace",
        "level": "Senior",
        "core_skills": ["spacecraft design", "orbital mechanics", "systems engineering"],
        "optional_skills": ["matlab", "simulink", "propulsion", "satellite systems"],
    },
    {
        "role": "Structural Analysis Engineer (Aerospace)",
        "domain": "Aerospace",
        "level": "Senior",
        "core_skills": ["structural analysis", "fea", "ansys", "stress analysis"],
        "optional_skills": ["fatigue analysis", "composites", "nastran", "abaqus"],
    },
    {
        "role": "Robotics Engineer",
        "domain": "Robotics",
        "level": "Mid to Senior",
        "core_skills": ["robotics", "ros", "python", "c++"],
        "optional_skills": ["robot operating system", "control systems", "computer vision", "embedded systems", "matlab", "simulink", "kinematics", "dynamics", "slam", "path planning"],
    },
    {
        "role": "ROS Developer",
        "domain": "Robotics",
        "level": "Mid",
        "core_skills": ["ros", "python", "c++", "robotics"],
        "optional_skills": ["ros2", "gazebo", "rviz", "slam", "navigation", "sensor integration"],
    },
    {
        "role": "Autonomous Systems Engineer",
        "domain": "Robotics/AI",
        "level": "Senior",
        "core_skills": ["autonomous systems", "robotics", "machine learning", "computer vision"],
        "optional_skills": ["ros", "slam", "path planning", "sensor fusion", "lidar", "perception"],
    },
    {
        "role": "Controls Engineer",
        "domain": "Robotics/Automation",
        "level": "Mid to Senior",
        "core_skills": ["control systems", "pid", "matlab", "simulink"],
        "optional_skills": ["plc", "motion control", "industrial automation", "scada", "labview"],
    },
    {
        "role": "Perception Engineer",
        "domain": "Robotics/AI",
        "level": "Mid to Senior",
        "core_skills": ["computer vision", "deep learning", "object detection", "sensor fusion"],
        "optional_skills": ["lidar", "radar", "camera calibration", "slam", "ros", "pytorch", "opencv"],
    },
    {
        "role": "Motion Planning Engineer",
        "domain": "Robotics",
        "level": "Senior",
        "core_skills": ["path planning", "motion planning", "robotics", "algorithms"],
        "optional_skills": ["ros", "slam", "collision avoidance", "optimization", "c++", "python"],
    },
    {
        "role": "IoT Engineer",
        "domain": "IoT",
        "level": "Mid",
        "core_skills": ["iot", "internet of things", "embedded systems", "mqtt"],
        "optional_skills": ["arduino", "raspberry pi", "esp32", "sensors", "cloud integration", "aws iot", "azure iot", "python"],
    },
    {
        "role": "Industrial Automation Engineer",
        "domain": "Automation",
        "level": "Mid",
        "core_skills": ["plc", "scada", "automation", "industrial control"],
        "optional_skills": ["hmi", "siemens", "allen bradley", "ladder logic", "sensors", "actuators", "robotics"],
    },
    {
        "role": "Mechatronics Engineer",
        "domain": "Robotics/Mechanical",
        "level": "Mid to Senior",
        "core_skills": ["mechatronics", "embedded systems", "control systems", "mechanical design"],
        "optional_skills": ["robotics", "plc", "matlab", "solidworks", "sensors", "actuators"],
    },
    {
        "role": "SLAM Engineer",
        "domain": "Robotics/AI",
        "level": "Senior",
        "core_skills": ["slam", "robotics", "computer vision", "sensor fusion"],
        "optional_skills": ["ros", "lidar", "kalman filter", "localization", "mapping", "c++"],
    },
    {
        "role": "Sensor Integration Engineer",
        "domain": "Robotics",
        "level": "Mid",
        "core_skills": ["sensors", "embedded systems", "ros", "hardware integration"],
        "optional_skills": ["lidar", "camera", "imu", "gps", "data acquisition", "python", "c++"],
    },
    {
        "role": "Robot Software Engineer",
        "domain": "Robotics",
        "level": "Mid to Senior",
        "core_skills": ["ros", "python", "c++", "robotics"],
        "optional_skills": ["control systems", "kinematics", "simulation", "embedded systems"],
    },
    {
        "role": "Chemical Engineer",
        "domain": "Chemical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["chemical engineering", "process engineering", "aspen plus"],
        "optional_skills": ["chemcad", "hysys", "process control", "thermodynamics", "reaction engineering", "mass transfer", "heat transfer"],
    },
    {
        "role": "Process Engineer",
        "domain": "Chemical Engineering",
        "level": "Mid",
        "core_skills": ["process engineering", "chemical engineering", "process optimization"],
        "optional_skills": ["aspen plus", "process control", "six sigma", "lean manufacturing"],
    },
    {
        "role": "Biomedical Engineer",
        "domain": "Biomedical Engineering",
        "level": "Mid to Senior",
        "core_skills": ["biomedical engineering", "medical devices", "biology"],
        "optional_skills": ["matlab", "signal processing", "image processing", "fda regulations", "clinical trials"],
    },
    {
        "role": "Bioinformatics Engineer",
        "domain": "Biomedical/Data",
        "level": "Mid to Senior",
        "core_skills": ["bioinformatics", "python", "r", "genomics"],
        "optional_skills": ["machine learning", "statistics", "dna sequencing", "proteomics", "biopython", "data analysis"],
    },
    {
        "role": "Pharmaceutical Engineer",
        "domain": "Chemical/Pharma",
        "level": "Mid to Senior",
        "core_skills": ["pharmaceutical engineering", "gmp", "process validation"],
        "optional_skills": ["quality control", "chemical engineering", "regulatory compliance", "fda"],
    },
    {
        "role": "Materials Scientist",
        "domain": "Materials Science",
        "level": "Senior/PhD",
        "core_skills": ["materials science", "materials characterization", "research"],
        "optional_skills": ["nanotechnology", "polymers", "composites", "metallurgy", "microscopy"],
    },
    {
        "role": "Polymer Engineer",
        "domain": "Materials/Chemical",
        "level": "Mid to Senior",
        "core_skills": ["polymers", "materials science", "chemical engineering"],
        "optional_skills": ["processing", "testing", "characterization", "extrusion", "injection molding"],
    },
    {
        "role": "Environmental Health & Safety Engineer",
        "domain": "Chemical/Environmental",
        "level": "Mid",
        "core_skills": ["ehs", "safety management", "environmental compliance"],
        "optional_skills": ["osha", "risk assessment", "incident investigation", "training"],
    },
    {
        "role": "Renewable Energy Engineer",
        "domain": "Energy",
        "level": "Mid to Senior",
        "core_skills": ["renewable energy", "solar energy", "power systems"],
        "optional_skills": ["wind energy", "pv systems", "energy storage", "grid integration", "matlab", "pvsyst", "homer"],
    },
    {
        "role": "Solar Engineer",
        "domain": "Energy",
        "level": "Mid",
        "core_skills": ["solar energy", "pv systems", "autocad"],
        "optional_skills": ["pvsyst", "helioscope", "system design", "inverters", "energy storage"],
    },
    {
        "role": "Wind Energy Engineer",
        "domain": "Energy",
        "level": "Mid to Senior",
        "core_skills": ["wind energy", "wind turbines", "aerodynamics"],
        "optional_skills": ["cfd", "structural analysis", "site assessment", "matlab"],
    },
    {
        "role": "Energy Analyst",
        "domain": "Energy/Data",
        "level": "Mid",
        "core_skills": ["energy analysis", "data analysis", "excel"],
        "optional_skills": ["python", "energy modeling", "optimization", "power bi", "renewable energy"],
    },
    {
        "role": "Battery Engineer",
        "domain": "Energy/Electrical",
        "level": "Mid to Senior",
        "core_skills": ["battery technology", "energy storage", "electrochemistry"],
        "optional_skills": ["bms", "battery management system", "lithium ion", "testing", "thermal management"],
    },
    {
        "role": "Electric Vehicle Engineer",
        "domain": "Automotive/Energy",
        "level": "Mid to Senior",
        "core_skills": ["electric vehicles", "battery technology", "power electronics"],
        "optional_skills": ["motor control", "bms", "charging systems", "matlab", "simulink"],
    },
    {
        "role": "Energy Storage Engineer",
        "domain": "Energy",
        "level": "Mid to Senior",
        "core_skills": ["energy storage", "battery technology", "power systems"],
        "optional_skills": ["bms", "grid integration", "renewable energy", "modeling"],
    },
    {
        "role": "Grid Engineer",
        "domain": "Electrical/Energy",
        "level": "Senior",
        "core_skills": ["power systems", "grid integration", "electrical engineering"],
        "optional_skills": ["renewable energy", "smart grid", "scada", "load flow", "protection"],
    },
    {
        "role": "Product Manager",
        "domain": "Product Management",
        "level": "Mid to Senior",
        "core_skills": ["product management", "product strategy", "roadmapping", "stakeholder management"],
        "optional_skills": ["agile", "scrum", "data analysis", "user research", "jira", "a/b testing", "product analytics"],
    },
    {
        "role": "Technical Product Manager",
        "domain": "Product Management",
        "level": "Senior",
        "core_skills": ["product management", "technical background", "api", "software development"],
        "optional_skills": ["agile", "sql", "python", "system design", "architecture"],
    },
    {
        "role": "Project Manager",
        "domain": "Project Management",
        "level": "Mid to Senior",
        "core_skills": ["project management", "agile", "scrum", "stakeholder management"],
        "optional_skills": ["pmp", "jira", "risk management", "budgeting", "ms project", "kanban"],
    },
    {
        "role": "Scrum Master",
        "domain": "Agile/PM",
        "level": "Mid",
        "core_skills": ["scrum", "agile", "facilitation", "jira"],
        "optional_skills": ["csm", "coaching", "sprint planning", "retrospectives", "kanban"],
    },
    {
        "role": "Program Manager",
        "domain": "Project Management",
        "level": "Senior",
        "core_skills": ["program management", "project management", "leadership", "strategy"],
        "optional_skills": ["agile", "stakeholder management", "risk management", "portfolio management"],
    },
    {
        "role": "Technical Project Manager",
        "domain": "Project Management",
        "level": "Mid to Senior",
        "core_skills": ["project management", "agile", "technical background"],
        "optional_skills": ["software development", "jira", "scrum", "devops", "cloud"],
    },
    {
        "role": "Delivery Manager",
        "domain": "Project Management",
        "level": "Mid to Senior",
        "core_skills": ["delivery management", "agile", "project management"],
        "optional_skills": ["scrum", "kanban", "stakeholder management", "jira"],
    },
    {
        "role": "Product Owner",
        "domain": "Product/Agile",
        "level": "Mid",
        "core_skills": ["product owner", "agile", "scrum", "backlog management"],
        "optional_skills": ["user stories", "jira", "stakeholder management", "prioritization"],
    },
    {
        "role": "Business Analyst (Technical)",
        "domain": "Analysis",
        "level": "Mid",
        "core_skills": ["business analysis", "requirements gathering", "documentation"],
        "optional_skills": ["sql", "jira", "agile", "process modeling", "stakeholder management"],
    },
    {
        "role": "Solutions Architect",
        "domain": "Architecture",
        "level": "Senior",
        "core_skills": ["solution architecture", "system design", "cloud", "aws"],
        "optional_skills": ["azure", "gcp", "microservices", "rest api", "enterprise architecture"],
    },
    {
        "role": "Enterprise Architect",
        "domain": "Architecture",
        "level": "Senior/Lead",
        "core_skills": ["enterprise architecture", "solution architecture", "strategy"],
        "optional_skills": ["togaf", "cloud", "system design", "integration", "governance"],
    },
    {
        "role": "UX Designer",
        "domain": "Design",
        "level": "Mid",
        "core_skills": ["ux design", "user research", "wireframing", "prototyping"],
        "optional_skills": ["figma", "sketch", "adobe xd", "usability testing", "user interviews"],
    },
    {
        "role": "UI Designer",
        "domain": "Design",
        "level": "Mid",
        "core_skills": ["ui design", "visual design", "figma"],
        "optional_skills": ["sketch", "adobe xd", "prototyping", "design systems", "css"],
    },
    {
        "role": "UI/UX Designer",
        "domain": "Design",
        "level": "Mid",
        "core_skills": ["ui design", "ux design", "figma", "prototyping"],
        "optional_skills": ["user research", "wireframing", "sketch", "adobe xd", "interaction design"],
    },
    {
        "role": "Product Designer",
        "domain": "Design",
        "level": "Mid to Senior",
        "core_skills": ["product design", "ui design", "ux design", "figma"],
        "optional_skills": ["user research", "prototyping", "design systems", "user testing"],
    },
    {
        "role": "Sales Engineer",
        "domain": "Sales",
        "level": "Mid",
        "core_skills": ["technical sales", "product demo", "communication", "presentation"],
        "optional_skills": ["crm", "salesforce", "solution selling", "customer engagement"],
    },
    {
        "role": "Digital Marketing Specialist",
        "domain": "Marketing",
        "level": "Entry to Mid",
        "core_skills": ["digital marketing", "seo", "sem", "social media marketing"],
        "optional_skills": ["google ads", "facebook ads", "content marketing", "email marketing", "analytics"],
    },
    {
        "role": "SEO Specialist",
        "domain": "Marketing",
        "level": "Entry to Mid",
        "core_skills": ["seo", "keyword research", "google analytics"],
        "optional_skills": ["sem", "content strategy", "link building", "technical seo", "ahrefs", "semrush"],
    },
    {
        "role": "Content Writer",
        "domain": "Content",
        "level": "Entry to Mid",
        "core_skills": ["content writing", "copywriting", "communication"],
        "optional_skills": ["seo", "blogging", "technical writing", "editing"],
    },
    {
        "role": "Technical Writer",
        "domain": "Documentation",
        "level": "Mid",
        "core_skills": ["technical writing", "documentation", "communication"],
        "optional_skills": ["api documentation", "user manuals", "markdown", "git", "confluence"],
    },
    {
        "role": "Growth Hacker",
        "domain": "Marketing/Product",
        "level": "Mid",
        "core_skills": ["growth hacking", "marketing", "data analysis", "a/b testing"],
        "optional_skills": ["sql", "python", "analytics", "experimentation", "product marketing"],
    },
    {
        "role": "CRM Manager",
        "domain": "Sales/Marketing",
        "level": "Mid",
        "core_skills": ["crm", "salesforce", "customer relationship management"],
        "optional_skills": ["marketing automation", "data analysis", "hubspot", "analytics"],
    },
    {
        "role": "Operations Manager",
        "domain": "Operations",
        "level": "Mid to Senior",
        "core_skills": ["operations management", "process improvement", "leadership"],
        "optional_skills": ["supply chain", "logistics", "six sigma", "project management"],
    },
    {
        "role": "Supply Chain Analyst",
        "domain": "Operations/Data",
        "level": "Mid",
        "core_skills": ["supply chain", "data analysis", "excel", "forecasting"],
        "optional_skills": ["python", "sql", "sap", "logistics", "inventory management"],
    },
    {
        "role": "HR Analyst",
        "domain": "HR/Data",
        "level": "Mid",
        "core_skills": ["hr analytics", "data analysis", "excel"],
        "optional_skills": ["python", "tableau", "power bi", "people analytics", "hris"],
    },
    {
        "role": "Ethical Hacker",
        "domain": "Cybersecurity",
        "level": "Senior",
        "core_skills": ["penetration testing", "ethical hacking", "cybersecurity", "linux"],
        "optional_skills": ["kali linux", "metasploit", "burp suite", "owasp", "ceh", "oscp"],
    },
    {
        "role": "Blockchain Architect",
        "domain": "Blockchain",
        "level": "Senior",
        "core_skills": ["blockchain", "architecture", "distributed systems", "cryptography"],
        "optional_skills": ["ethereum", "solidity", "hyperledger", "smart contracts", "consensus algorithms"],
    },
    {
        "role": "AR/VR Developer",
        "domain": "Gaming/XR",
        "level": "Mid",
        "core_skills": ["unity", "ar", "vr", "c#"],
        "optional_skills": ["unreal engine", "3d modeling", "arkit", "arcore", "oculus", "hololens"],
    },
    {
        "role": "3D Artist / Modeler",
        "domain": "Design/Gaming",
        "level": "Mid",
        "core_skills": ["3d modeling", "blender", "maya"],
        "optional_skills": ["3ds max", "texturing", "rigging", "animation", "substance painter"],
    },
    {
        "role": "Video Editor",
        "domain": "Media",
        "level": "Entry to Mid",
        "core_skills": ["video editing", "premiere pro", "final cut pro"],
        "optional_skills": ["after effects", "color grading", "motion graphics", "davinci resolve"],
    },
    {
        "role": "Graphic Designer",
        "domain": "Design",
        "level": "Entry to Mid",
        "core_skills": ["graphic design", "photoshop", "illustrator"],
        "optional_skills": ["indesign", "figma", "branding", "typography", "layout design"],
    },
    {
        "role": "Audio Engineer",
        "domain": "Media",
        "level": "Mid",
        "core_skills": ["audio engineering", "sound design", "mixing", "mastering"],
        "optional_skills": ["pro tools", "ableton", "logic pro", "recording", "acoustics"],
    },
    {
        "role": "Network Engineer",
        "domain": "IT/Networking",
        "level": "Mid to Senior",
        "core_skills": ["networking", "cisco", "routing", "switching"],
        "optional_skills": ["ccna", "ccnp", "firewall", "vpn", "tcp/ip", "network security"],
    },
    {
        "role": "System Administrator",
        "domain": "IT",
        "level": "Mid",
        "core_skills": ["linux", "windows server", "system administration"],
        "optional_skills": ["active directory", "powershell", "bash", "virtualization", "vmware", "backup"],
    },
    {
        "role": "IT Support Engineer",
        "domain": "IT",
        "level": "Entry to Mid",
        "core_skills": ["technical support", "troubleshooting", "windows", "networking"],
        "optional_skills": ["active directory", "help desk", "ticketing", "hardware support"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    # HUMAN RESOURCES & RECRUITMENT
    # ─────────────────────────────────────────────────────────────────────────
    {
        "role": "HR Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["recruiting", "employee relations", "performance management", "compensation"],
        "optional_skills": ["payroll", "benefits administration", "hr strategy", "organizational development", "change management"],
    },
    {
        "role": "HR Business Partner",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["business partnering", "hr strategy", "employee relations", "stakeholder management"],
        "optional_skills": ["organizational development", "talent management", "change management", "hr analytics"],
    },
    {
        "role": "Recruiter",
        "domain": "Human Resources",
        "level": "Entry to Mid",
        "core_skills": ["recruiting", "candidate sourcing", "job posting", "interview conduct"],
        "optional_skills": ["hiring", "recruitment marketing", "applicant tracking", "networking"],
    },
    {
        "role": "Talent Acquisition Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["recruiting", "talent acquisition", "candidate sourcing", "job posting"],
        "optional_skills": ["recruitment marketing", "hiring", "employer branding", "recruiting strategy"],
    },
    {
        "role": "HR Coordinator",
        "domain": "Human Resources",
        "level": "Entry",
        "core_skills": ["administrative", "employee records", "scheduling", "communication"],
        "optional_skills": ["benefits", "payroll", "training coordination", "scheduling"],
    },
    {
        "role": "Compensation & Benefits Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["compensation", "benefits administration", "salary planning", "payroll"],
        "optional_skills": ["equity compensation", "benefits design", "cost analysis", "compliance"],
    },
    {
        "role": "Payroll Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["payroll", "payroll processing", "tax compliance", "statutory compliance"],
        "optional_skills": ["benefits administration", "cost accounting", "hris", "audit"],
    },
    {
        "role": "Training & Development Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["training and development", "training design", "coaching", "learning management"],
        "optional_skills": ["instructional design", "e-learning", "mentoring", "corporate training"],
    },
    {
        "role": "L&D Specialist",
        "domain": "Human Resources",
        "level": "Entry to Mid",
        "core_skills": ["training and development", "training design", "corporate training", "learning management"],
        "optional_skills": ["instructional design", "e-learning", "coaching", "content development"],
    },
    {
        "role": "Employee Relations Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["employee relations", "conflict resolution", "grievance handling", "labor law"],
        "optional_skills": ["employee engagement", "performance management", "compliance", "mediation"],
    },
    {
        "role": "Organizational Development Manager",
        "domain": "Human Resources",
        "level": "Mid to Senior",
        "core_skills": ["organizational development", "change management", "culture building", "strategic planning"],
        "optional_skills": ["team development", "coaching", "hr strategy", "talent management"],
    },
    {
        "role": "HR Analyst",
        "domain": "Human Resources",
        "level": "Entry to Mid",
        "core_skills": ["hr analytics", "data analysis", "excel", "reporting"],
        "optional_skills": ["business intelligence", "metrics", "dashboards", "hris", "sql"],
    },
    {
        "role": "HRIS Administrator",
        "domain": "Human Resources",
        "level": "Entry to Mid",
        "core_skills": ["hris", "data management", "technical support", "employee records"],
        "optional_skills": ["system administration", "training", "troubleshooting", "documentation"],
    },
]

# Backward compatibility for existing imports in matcher/app code.
ROLE_DATABASE = COMPREHENSIVE_JOB_DATABASE


def get_all_roles():
    """Returns list of all role names."""
    return [job["role"] for job in COMPREHENSIVE_JOB_DATABASE]


def get_roles_by_domain(domain):
    """Returns all roles in a specific domain."""
    return [job for job in COMPREHENSIVE_JOB_DATABASE if job["domain"] == domain]


def get_all_domains():
    """Returns list of unique domains."""
    return list(set(job["domain"] for job in COMPREHENSIVE_JOB_DATABASE))


def search_roles_by_skill(skill):
    """Find all roles that require or prefer a specific skill."""
    matching_roles = []
    skill_lower = skill.lower()

    for job in COMPREHENSIVE_JOB_DATABASE:
        core_skills_lower = [s.lower() for s in job["core_skills"]]
        optional_skills_lower = [s.lower() for s in job["optional_skills"]]

        if skill_lower in core_skills_lower or skill_lower in optional_skills_lower:
            matching_roles.append(job)

    return matching_roles


if __name__ == "__main__":
    print(f"Total roles in database: {len(COMPREHENSIVE_JOB_DATABASE)}")
    print(f"Total domains: {len(get_all_domains())}")
    print(f"\nAll domains: {get_all_domains()}")
